<h1 align='center'><font color='red'> Task_4


1. [NumPy](#NumPy)
1. [oop](#oop)
3. [ProblemSolving](#ProblemSolving)


<a id='NumPy'></a>
<h1><font color='red'> NumPy

## 1.What does NumPy stand for?


#### A) Number Python
#### B)Numerator Python
#### C) Numerical Python
#### D)There is no full form, it is a stand-alone word  


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 2.What does the size attribute in numpy use to find?


#### A) number of items
#### B)shape
#### C) date & time
#### D)unique items
    

In [ ]:
A = False #@param {type:"boolean"}
B = True #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}

### 3.What is the purpose of zero() function?

#### A) To create a matrix with the first row and first column as 0
#### B) To create a matrix with diagonal elements as 0
#### C) To create a matrix with all elements as 0
#### D) To return an integer number 0


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}

<h1><font color='red'> Answer these question

### 4- create 1D, 2D and 3D arrays in NumPy? then returns the type of the elements stored in the NumPy array.

In [ ]:
# One-Dimensional array
import numpy as np

arr1 = np.array([1])
print(arr1.dtype)

int64


In [ ]:
# Two-Dimensional array
import numpy as np

arr2 = np.array([[1,1],
                 [1,1]])
print(arr2.dtype)

int64


In [ ]:
# Three-Dimensional array
import numpy as np

arr3 = np.array([[1,1,1],
                 [1,1,1],
                 [1,1,1]])

print(arr3.dtype)

int64


### 5-Reverse this array [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]] in two ways......

In [ ]:
# Method one
import numpy as np

array =  np.array([[[1,2,3,4],
                    [4,5,6,7],
                    [7,8,9,10]]])
array

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]]])

In [ ]:
from numpy.lib.twodim_base import flipud
# Method two
#>**hint**: use flipud function

import numpy as np

array =  np.array([[[1,2,3,4],
                    [4,5,6,7],
                    [7,8,9,10]]])

np.flipud(array)

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 7,  8,  9, 10]]])

## 6-Make this array as an array one dimensional

In [ ]:
import numpy as np
array =  np.array([[[1,2,3,4],
           [4,5,6,7],
           [7,8,9,10]]])

array.flatten()

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

## 7- Create a 3X2 integer array and Prints its attributes¶
* Note: The element must be a type of unsigned int16. And print the following Attributes:

- The shape of an array.
- Array dimensions.
- The Length of each element of the array in bytes

In [12]:
import numpy as np
arr = np.array([[1,2],
                [3,4],
                [5,6]], dtype=np.int16)

arr.shape

(3, 2)

### 8- Return array of odd rows and even columns from below numpy array

* # Ordering the values of each Key and the print the key witht highest value.


> **`sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])`**


# The output should be:
* `expexted output :
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]`

* `Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]`*

In [43]:
sampleArray = np.array([[3 ,6, 9, 12],
                        [15 ,18, 21, 24],
                        [27 ,30, 33, 36],
                        [39 ,42, 45, 48],
                        [51 ,54, 57, 60]])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


## 9-How is np.mean() different from np.average() in NumPy?

In [ ]:
np.mean()
# Compute the arithmetic mean without considering any weights
np.average()
# Compute the weighted average

np.mean() == np.average()
np.mean() != np.average(weights= [])

## 10-Count the frequency of a given positive value appearing in this NumPy array
## [1, 2, 1, 3, 5, 0, 0, 0, 2, 3] ?

In [20]:
import numpy as np
arr = np.array([1,2,1,3,5,0,0,0,2,3])
freq = np.count_nonzero(arr > 0) # +ve value
print(freq)

7


## 11-Show how is arr[:,0] different from arr[:,[0]]

In [28]:
arr = np.array([[1,2],
                [3,4],
                [5,6]])

print(arr[:,0], arr[:,0].shape)
# 1D array row vector
# returns first column values

[1 3 5] (3,)


In [29]:
print(arr[:,[0]],arr[:,[0]].shape)
# 2D array 3 rows and 1 column
# returns first column values as each value is row

[[1]
 [3]
 [5]] (3, 1)


### 12-How do you multiply these 2 NumPy array matrices [[15,16,17],[18,19,20],[21,22,23]]  &  [[20,21,22],[23,24,25],[26,27,28]] ?

In [15]:
import numpy as np
arr1 = np.array([[15,16,17],
                 [18,19,20],
                 [21,22,23]])

In [5]:
arr2 = np.array([[20,21,22],
                 [23,24,25],
                 [26,27,28]])

In [6]:
multi_arr = arr1 * arr2
multi_arr

array([[300, 336, 374],
       [414, 456, 500],
       [546, 594, 644]])

### 13 -Combine these 2 NumPy arrays [1,2,3] & [4,5,6] using vstack()     and hstack()

In [17]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

# <a id='oop'></a>
<h1><font color='red'> oop

# 1 - a "class" is ... </font>

<br> </br>
#### A) an instance variable
#### B) a code template for creating object
#### C) a function in python
#### D) a synonym for methods

In [ ]:
A = False #@param {type:"boolean"}
B = True #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


# 2- What is a "docstring" ?</font>
<br> </br>
#### A) it is a sting literal specified in source code that is used to explain or document a specific segment of code
#### B) it is a class method that allows working with string documents
#### C) it is an alternative name for instance vaeiables of type string apprearing in classes
#### D) it is a synonym for code comments

In [ ]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 3- Create a Bus class that inherits from the Vehicle class. Give the capacity argument of Bus.seating_capacity() a default value of 50.
- Use the following code for your parent Vehicle class:.
>   class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers


In [23]:
class Vehicle:
  def __init__(self, name, max_speed, mileage):
    self.name= name
    self.max_speed = max_speed
    self.mileage = mileage

  def seating_capacity(self, capacity):
    return f"The seating capacity of a {self.name} is {capacity} passengers"

class Bus(Vehicle):
  def seating_capacity(self, capacity = 50):
    return f"The seating capacity of a {self.name} is {capacity} passengers"

bus1 = Bus("Mercedes", 130 , 12)

print(bus1.seating_capacity())

The seating capacity of a Mercedes is 50 passengers


# <a id='ProblemSolving'></a>
<h1><font color='red'>Problem Solving


<a href='https://codeforces.com/problemset/problem/339/A'> **problem 1**

In [57]:
# Problem_1 Link:
s = input()

sum_s = s.split("+")
# print(sum_s)

sorted_sum_s = sorted(map(int,sum_s))
# print(sorted_sum_s)

req_s = "+".join(map(str,sorted_sum_s))
print(req_s)

1+1+3+1+3
1+1+1+3+3


<a href='https://codeforces.com/problemset/problem/118/A'> **problem 2**

In [47]:
# Problem_2 Link:
s = input()

s = s.lower()
vowels = ["A", "O", "Y", "E", "U", "I","a","o","y","e","u","i"]

for i in range(len(s)):
    if s[i] not in vowels:
        print("."+ s[i], end="")



Codeforces
.c.d.f.r.c.s